<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Reusable tool macro -->
  <xacro:macro name="tool" params="name mass length radius r g b a">
    <!-- Tool base link -->
    <link name="${name}_base">
      <visual>
        <geometry>
          <cylinder radius="${radius}" length="${length}"/>
        </geometry>
        <origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
        <material name="">
          <color rgba="${r} ${g} ${b} ${a}"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${radius*1.1}" length="${length*1.1}"/>
        </geometry>
        <origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
      </collision>
      <inertial>
        <mass value="${mass}"/>
        <inertia ixx="1e-3" ixy="0" ixz="0" iyy="1e-3" iyz="0" izz="1e-3"/>
      </inertial>
    </link>

    <!-- Tool mounting interface -->
    <link name="${name}_mount">
      <inertial>
        <mass value="0.01"/>
        <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6"/>
      </inertial>
    </link>

    <joint name="${name}_mount_joint" type="fixed">
      <parent link="${name}_base"/>
      <child link="${name}_mount"/>
      <origin xyz="0 0 ${length}" rpy="0 0 0"/>
    </joint>
    
    <!-- CRITICAL FIX: Connect tool to its dock initially -->
    <joint name="${name}_to_dock_joint" type="fixed">
      <parent link="${name}_dock_base"/>
      <child link="${name}_base"/>
      <origin xyz="0 0 0.08" rpy="0 0 0"/>
    </joint>
  </xacro:macro>

  <!-- Instantiate specific tools -->
  <xacro:tool name="gripper" mass="0.3" length="0.12" radius="0.012" r="0.8" g="0.2" b="0.2" a="1.0"/>
  <xacro:tool name="screwdriver" mass="0.2" length="0.18" radius="0.012" r="0.2" g="0.8" b="0.2" a="1.0"/>
  <xacro:tool name="camera" mass="0.15" length="0.08" radius="0.02" r="0.2" g="0.2" b="0.8" a="1.0"/>

</robot>